### ISSUE TITLE
Button hover css removed

### ISSUE THREAD

**Issue by EeshanKumar** [lisposter/angular-zeroclipboard#23]
My button uses an image sprite as a background. On hover, it moves the image so it looks pressed. Here is my CSS.

button:hover {
  background-position-x: 100%;
  padding: 2px 0 0 2px;
}

This means when the element gets the new class, "zeroclipboard-is-hover", my css hover no longer applies.

**Comment by lisposter** [comment]
@EeshanKumar Because there is a flash over the element, the element won't be hovered, so, it use flash to listen mouse event, and when the mouse is over the flash(also over the element), it create a css class named 'zeroclipboard-is-hover' for the element.

TL;DR
You should create a css class named `zeroclipboard-is-hover` with the style you want for button hovered.

``` css
.zeroclipboard-is-hover {
    background: url('your-sprite-image');
    background-position-x: 100%;
    padding: 2px 0 0 2px;
}
```
